INSERT INTO CVP_USERNAME.PRODUTO
(ID, NOME, PRECO)
VALUES(1, 'Notebook', 5000);
INSERT INTO CVP_USERNAME.PRODUTO
(ID, NOME, PRECO)
VALUES(2, 'Televisao 1', 9876.54);
INSERT INTO CVP_USERNAME.PRODUTO
(ID, NOME, PRECO)
VALUES(3, 'Televisao 2', 4567.89);